### ISSUE TITLE
Creation of parsers 

### ISSUE THREAD

**Issue by NEH-Alpha** [jonaslagoni/jonaslagoni#3]
I need help in creating parsers for Chronicle and NetEnrich, anyone aware of it , kindly help me out

**Comment by NEH-Alpha** [comment]
Anybody who can help

**Comment by jonaslagoni** [comment]
@NEH-Alpha i would reach out on the AsyncAPI slack channel 🙂

**Comment by NEH-Alpha** [comment]
> @NEH-Alpha i would reach out on the AsyncAPI slack channel 🙂

Can you share me the channel

**Comment by jonaslagoni** [comment]
You can find it on the AsyncAPI website

**Comment by NEH-Alpha** [comment]
> @NEH-Alpha i would reach out on the AsyncAPI slack channel 🙂

Not able to see this channel
